---
permalink: "pretty"
relative_permalinks: true

title: "Thoughtless Banter"
tagline: "Musings from a software engineer."
url: "http://thoughtlessbanter.com"
paginate: 1
baseurl: ""

sass:
  sass_dir: _sass
  style: :compressed

author:
  name: "John Bellone"
  url: "https://twitter.com/johnbellone"
  github: "johnbellone"
  email: "jbellone[at]bellone.us"
