# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Thoughtless Banter
tagline:             Musings from a software engineer.
url:                 http://thoughtlessbanter.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              John Bellone
  url:               https://twitter.com/johnbellone
  email:             john.bellone.jr@gmail.com
